# プロジェクトのルートディレクトリに .codeclimate.yml（先頭に .）として保存してください
# 非推奨ライブラリは除外
languages:
  Ruby: false
  JavaScript: true
  PHP: true
exclude_paths:
- core/libs/db/*
- core/libs/kumbia_active_record/*
- core/libs/acl/*