<footer>
    <div class="col-6">
        <ul class="inline">
            <li><a href="https://kumbiaphp.com/">KumbiaPHP Framework</a> |</li>
            <li><a href="https://github.com/KumbiaPHP/KumbiaPHP" title="KumbiaPHP の GitHub リポジトリ。フォークしたり Star を付けることができます。">Github</a> |</li>
            <li><a href="https://github.com/KumbiaPHP/Documentation/tree/master/es">マニュアル</a> |</li>
            <li><a href="https://wiki.kumbiaphp.com/">Wiki</a> |</li>
            <li><a href="https://wiki.kumbiaphp.com/Licencia" title="New BSD ライセンス">ライセンス</a></li>
        </ul>
    </div>
    <div class="col-6 text-right">
        <p>オンラインサポート:
            <a href="https://slack.kumbiaphp.com" title="KumbiaPHP に関する質問、コメント、アイデア提案、バグ報告などができるチャットです。"><img src="https://slack.kumbiaphp.com/badge.svg" alt="KumbiaPHP Slack"></a> |
            <a href="https://groups.google.com/group/kumbia" title="KumbiaPHP のメーリングリスト。質問やコメント、アイデア提案、バグ報告などに利用できます。">グループ</a> |
            <a href="https://foro.kumbiaphp.com" title="KumbiaPHP のフォーラム。質問やコメント、アイデア提案、バグ報告などに利用できます。">フォーラム</a>
        </p>
    </div>
    <div class="col-12 text-center">
        <a href="https://wiki.kumbiaphp.com/Team_Development_KumbiaPHP_Framework">© 2007 - <?= date('Y'); ?> KumbiaPHP Team</a>
    </div>
    <div class="col-12 text-center">
        <?= '実行時間: ', round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT']) * 1000, 4), ' ms / メモリ使用量: ', number_format(memory_get_usage() / 1048576, 3), ' MB'; ?>
    </div>
</footer>
