<!DOCTYPE html>
<html lang="ja">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>KumbiaPHP フレームワーク</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php Tag::css('kumbia') ?>
  <?= Html::includeCss() ?>
</head>
<body>
<div class="container">
  <header class="row">
      <div class="col-8">
          <?= Html::link('', Html::img('kumbiaphp.svg', 'KumbiaPHP ロゴ'), 'title="ホーム"') ?>
      </div>
      <div class="col-4 text-right">
          アプリケーション: <strong><?= basename(dirname(APP_PATH)) ?></strong> (<?= PRODUCTION ? '本番' : '開発' ?>)
      </div>
  </header>
  <?php View::content() ?>
  <?php View::partial('kumbia/footer') ?>
</div>
</body>
</html>
